langfuse:
  salt:
    secretKeyRef:
      name: langfuse-general
      key: salt
  
  nextauth:
    url: "http://localhost:3000"
    secret:
      secretKeyRef:
        name: langfuse-nextauth-secret
        key: nextauth-secret
  
  web:
    image:
      repository: "docker.io/langfuse/langfuse"
    pod:
      additionalEnv:
        - name: DATABASE_URL
          value: "postgresql://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@$(DATABASE_HOST):5432/$(DATABASE_NAME)"
  
  worker:
    image:
      repository: "docker.io/langfuse/langfuse-worker"

postgresql:
  auth:
    username: langfuse
    database: postgres_langfuse
    existingSecret: langfuse-postgresql-auth
    secretKeys:
      userPasswordKey: password
      adminPasswordKey: postgres-password

clickhouse:
  auth:
    existingSecret: langfuse-clickhouse-auth
    existingSecretKey: password

redis:
  auth:
    existingSecret: langfuse-redis-auth
    existingSecretPasswordKey: password

s3:
  auth:
    existingSecret: langfuse-s3-auth
    rootUserSecretKey: rootUser
    rootPasswordSecretKey: rootPassword
