apiVersion: v1
kind: Service
metadata:
  name: aegra-service
  namespace: aegra
  labels:
    app.kubernetes.io/name: aegra
    app.kubernetes.io/part-of: aegra
spec:
  selector:
    app.kubernetes.io/name: aegra
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP